// Copyright (c) 2018 Stephan Unverwerth
// This code is licensed under MIT license (See LICENSE for details)

#ifndef ast_nodes_h
#define ast_nodes_h

#include "ArrayLitExpression.h"
#include "ArrayTypeExpression.h"
#include "AssignExpression.h"
#include "BinopExpression.h"
#include "BlockStatement.h"
#include "CallExpression.h"
#include "CastExpression.h"
#include "EnumElement.h"
#include "Expression.h"
#include "ExpressionStatement.h"
#include "FieldDeclaration.h"
#include "FunctionDeclaration.h"
#include "GenericParameter.h"
#include "GenericReificationExpression.h"
#include "IdExpression.h"
#include "IfStatement.h"
#include "ImportStatement.h"
#include "InterfaceDeclaration.h"
#include "InterfaceMethodDeclaration.h"
#include "InterfaceFieldDeclaration.h"
#include "IsExpression.h"
#include "LitExpression.h"
#include "MapLitExpression.h"
#include "NewExpression.h"
#include "Node.h"
#include "NullableTypeExpression.h"
#include "Parameter.h"
#include "PostfixExpression.h"
#include "ReturnStatement.h"
#include "ScopeExpression.h"
#include "Statement.h"
#include "SubscriptExpression.h"
#include "ThisExpression.h"
#include "TypeAliasDeclaration.h"
#include "TypeDeclaration.h"
#include "UnaryExpression.h"
#include "UnionTypeExpression.h"
#include "VarDeclaration.h"
#include "WhileStatement.h"

// types
#include "ArrayType.h"
#include "BoolType.h"
#include "ClassDeclaration.h"
#include "EnumDeclaration.h"
#include "FloatType.h"
#include "FunctionType.h"
#include "IntType.h"
#include "InvalidType.h"
#include "ModuleDeclaration.h"
#include "NullType.h"
#include "OverloadedFunctionType.h"
#include "PointerType.h"
#include "TypeType.h"
#include "UnionType.h"
#include "VoidType.h"


#endif